apiVersion: apps/v1
kind: Deployment
metadata:
  name: trending-stocks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trending-stocks
  template:
    metadata:
      labels:
        app: trending-stocks
    spec:
      containers:
      - name: trending-stocks-container
        image: gcr.io/trending-stocks/trending-stocks-container
        env:
        - name: FIRESTORE_PROJECT_ID
          value: trending-stocks
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: trending-stocks-service
spec:
  selector:
    app: trending-stocks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

